### PR TITLE
loss accounts for regularization penalty applied to biases

### PR DESCRIPTION
**Pull request by dselivanov**
when calculating loss take into account regularization penalty applied to biases
cc @david-cortes

### CODE REVIEW

**Comment by david-cortes** [comment]
I see now it's calculating the matrices used for Cholesky also when using CG. Those would be better written under an "if" as they aren't used for CG and are the slowest part of the procedure.

**Comment by david-cortes** [comment]
For the "fixme" point, the biases would actually be initialized to zeros if there is no data for a given user/item, so it doesn't make a difference.

**Comment by dselivanov** [comment]
> I see now it's calculating the matrices used for Cholesky also when using CG. Those would be better written under an "if" as they aren't used for CG and are the slowest part of the procedure.

Not sure I understand what you mean

**Comment by david-cortes** [comment]
Lines 137-139  in SolverAlsWrmf.cpp under this commit.

**Comment by dselivanov** [comment]
Ah, I see. I've introduced this issue when added CG solver.

**Pull request merged**
