### PR TITLE
Add functions for reading and writing sparse matrices

### PR DESCRIPTION
**Pull request by david-cortes**
Adapted from here: https://github.com/david-cortes/readsparse

### CODE REVIEW

**Comment by dselivanov** [comment]
Hi @david-cortes. Thanks for contribution and PR. Do you have any plans to publish `readsparse` to CRAN? I'm thinking what is the advantage of having such functionality here compared to relying on your `readsparse` or less feature rich [sparsio](https://cran.r-project.org/web/packages/sparsio/)?

**Comment by david-cortes** [comment]
I wanted to merge `readsparse` here instead of pushing it to CRAN as I think it's quite wasteful and harder for discoverability to create a separate package just for that.

From a logical POV, it really ought to be in `Matrix`, but that package doesn't accept contributions like this, and `rsparse` is already dealing with CSR matrices and the kind of data that is handled in LibSVM format.

**Comment by david-cortes** [comment]
Will better move to a new pacakge along with https://github.com/rexyai/rsparse/pull/63

**Comment by dselivanov** [comment]
Initially I've created 2 separate packages - one is Matrix enhancement (extended CSR functionality, sparse-dense products with openmp, etc) and the second is about matrix factorizations. Then at some point it was more convenient to develop everything in one place and I combined them into 1 repository. Now it might make sense to create a base pkg which which mainly enhance Matrix pkg and leave factorizations aside.

>From a logical POV, it really ought to be in Matrix, but that package doesn't accept contributions like this
Did you reach out Martin Maechler? That was my intention,  but I never did so. Mb this is the right time.

**Comment by david-cortes** [comment]
I haven’t contacted Martin, but from what I see in the R-Forge page, the lack of first-class support for some classes seems to be intentional:
https://r-forge.r-project.org/tracker/index.php?func=detail&aid=6186&group_id=61&atid=296

Apart from that, it’s all C code and doesn’t use GIT for version control, so it’d be very hard for me to send any kind of PR there.

**Comment by david-cortes** [comment]
Good to know. Created a separate package in the meantime: https://github.com/david-cortes/MatrixExtra

**Pull request closed without merging**
