### PR TITLE
Improve performance tips in readme

### PR DESCRIPTION
**Pull request by david-cortes**
This PR modifies and expands a bit the section about performance tips:
* `-mavx` is already implied by `-march=native` when the CPU supports AVX. If the CPU does not support AVX, it will generate code that doesn't run.
* `-ffast-math` is a very dangerous option for a general `Makevars`, especially for other packages which handle NAs. Additionally, it has pretty much no effect for `rsparse` (at least for `WRMF`). I didn't see any speed up from `-O3` compared to `-O2` either.
* Added some sections about BLAS.

Additionally, the Makevars files had the pre-processor flags under the C++ flags - this can generate problems in some of the CRAN builds (particularly debian-clang), so I moved them to `PKG_CPPFLAGS`.

### CODE REVIEW

**Comment by dselivanov** [comment]
All but this line look reasonable for me
> On Linux, these optimizations can also be added by modifying the global `Makeconf` file - in Debian and its derivatives (such as Ubuntu), this file will typically be under `/etc/R/`, and can be modified by applying these simple text replacements: `-O2` -> `-O3`, `-msse2` -> `-march=native` (assuming R was installed from system repositories and this is an x86-64 CPU). Be aware that this file is used for compilation of **all** R packages.

I would not recommend to change system-wise settings for anyone. Amending ~/.R/Makevars allows to achieve same effect, but on user level.

**Comment by david-cortes** [comment]
In Debian at least, those would get added after the global ones, so it would put for example `... -O3 ... -O2` and it would have no effect.

**Comment by dselivanov** [comment]
R adds global flags from `/etc/R/` first, then flags from `~/.R/Makevars`. So `~/.R/Makevars` will amend global ones. As I understand here you mean the same?
> In Debian at least, those would get added after the global ones, so it would put for example ... -O3 ... -O2 and it would have no effect.

**Comment by david-cortes** [comment]
Sorry, meant to say that the flags from the user Makevars are added before the flags from the global Makeconf, so O3 in the user Makevars gets cancelled by the O2 in the global Makeconf.

**Comment by dselivanov** [comment]
> Sorry, meant to say that the flags from the user Makevars are added before the flags from the global Makeconf, so O3 in the user Makevars gets cancelled by the O2 in the global Makeconf.

Just double checked that on debian docker image. I can't confirm - user flags from `~/.R/Makevars` appended **after** global from `/etc/R/Makeconf`.

**Comment by david-cortes** [comment]
Did some extra experiments. Turns out that:
* `CXXFLAGS` doesn't get added.
* `CXX11FLAGS` gets added after.
* `PKG_CXXFLAGS` gets added before.

Will modify it.

**Pull request merged**
