### PR TITLE
re-arrange omp parallel region to make more efficient memory allocattions

### PR DESCRIPTION
**Pull request by dselivanov**
Related to #72.
@david-cortes now I don't see much difference with cmfrec when using CG solver. On lastfm360 dataset cmfrec is ~43 sec, rsparse ~46 sec. I follow your data split from [split_lastfm_data.ipynb](https://github.com/david-cortes/cmfrec/blob/master/benchmark/split_lastfm_data.ipynb).

```r
library(Matrix)
library(cmfrec)
library(rsparse)
X_all = readRDS("~/Downloads/X_all.rds")

X_all_coo = as(X_all, 'TsparseMatrix')

# X_all2 = as(t(X_all), 'RsparseMatrix')
N_THREAD = 4
N_ITER = 10
RANK = 64

options("rsparse_omp_threads" = N_THREAD)
system.time({
  set.seed(123)
  model_cg <- WRMF$new(feedback="implicit", rank=RANK, lambda=5,
                       solver="conjugate_gradient",
                       with_global_bias=FALSE, with_user_item_bias=FALSE)
  ignored <- model_cg$fit_transform(X_all, n_iter=N_ITER, convergence_tol=-1)
})

system.time({
  model_chol <- CMF_implicit(X_all_coo, k=RANK, niter=N_ITER, lambda=5,
                             use_cg=TRUE,finalize_chol=TRUE,
                             verbose=TRUE, precompute_for_predictions=FALSE, nthreads=N_THREAD)
})

```

When, however, using Cholesky solver, cmfrec is quite faster - cmfrec ~44 sec, rsparse ~52 sec. Looks like you use some specialized solver (`dposv`) from LAPACK? Not sure how armadillo handels "fast" solve.

```r
N_THREAD = 4
N_ITER = 10
RANK = 32

options("rsparse_omp_threads" = N_THREAD)
system.time({
  set.seed(123)
  model_cg <- WRMF$new(feedback="implicit", rank=RANK, lambda=5,
                       solver="cholesky",
                       with_global_bias=FALSE, with_user_item_bias=FALSE)
  ignored <- model_cg$fit_transform(X_all, n_iter=N_ITER, convergence_tol=-1)
})

system.time({
  model_chol <- CMF_implicit(X_all_coo, k=RANK, niter=N_ITER, lambda=5,
                             use_cg=FALSE,finalize_chol=TRUE,
                             verbose=TRUE, precompute_for_predictions=FALSE, nthreads=N_THREAD)
})
```

### CODE REVIEW

**Comment by david-cortes** [comment]
Thanks for looking into this. Gave it a try and can now see that the Cholesky solver is a bit faster (albeit still slightly slower than it used to be several versions ago of all the underlying software like gcc/openblas/arma/etc.), but I'm still seeing quite a large difference in the CG solver w.r.t. `cmfrec`:

For this example:
https://github.com/david-cortes/cmfrec/blob/6629cd1f88862135eb38e67c8316c428acca969f/benchmark/benchmark_implicit_r.Rmd#L135

It takes ~40s on my machine compared to ~31s for `cmfrec`, for example (50 factors, 15 iterations, last one with Cholesky).

As for the Cholesky solver, I've found some notes from armadillo from several versions ago stating that their solver should end up calling `posv` when appropriate, so I don't think it'd make a difference. However, what I found to make a large difference in the timings is the computation of `t(X)*X`, as it seems that such operation (`syrk`), when done single-threaded, is slower in both MKL and OpenBLAS compared to a naive loop optimized by gcc with `-march=native`. I'm pretty sure armadillo doesn't end up calling `syrk` though, as many versions ago the Cholesky solver in `rsparse` was already having comparable timings as the current one in `cmfrec`.

I'm also wondering whether the timings degradation that I was seeing might have to do with gcc, linux security patches, and so on; since downgrading `rsparse` doesn't change the CG timings for me.

**Comment by dselivanov** [comment]
@david-cortes I've pushed updates in R code to avoid double work in `transform`. Now on my machine `rsparse` is even slightly faster compared to `cmfrec`. One important thing - I launch R as `OMP_NUM_THREADS=1 R ` to limit OpenMP threads (affects both cmfrec and rsparse).
It's interesting that if I don't specify `OMP_NUM_THREADS=1` even if I disable OpenMP in R, Armadillo and wherever I can, still app uses more CPU than allowed (when using htop I see up to 600% even if only 4 threads allowed).

For the Cholesky I still can't match cmfrec and I fill you are right - this [line](https://github.com/rexyai/rsparse/blob/c91b67633a585b31b5711bb02247c0ab60378ad0/inst/include/wrmf_implicit.hpp#L208) might be a bottleneck.

I don't think timings regressions are related to gcc (or system) change. I believe that the code base changed significantly since v0.3-0.4.

**Comment by david-cortes** [comment]
Did some additional testing with the latest commit here. What I am seeing is that, if I set the number threads to the number of physical cores in my machine, then `rsparse` here has similar timings as `cmfrec` (32.9s vs. 32.7s for the example above), but if I increase the number of threads to the number of logical cores, then `rsparse` becomes slower while `cmfrec` becomes slightly faster. Not sure why that would happen.

As for the thread usage, it might be that you are using a BLAS / LAPACK library that doesn't use OpenMP for multithreading (e.g. MKL, OpenBLAS-pthreads), in which case you'd additionally need to set the number of threads for that library, but I don't think such a thing should be the responsibility of `rsparse`.

**Comment by david-cortes** [comment]
Also for reference, in an apple ARM processor where logical cores match with physical cores, the timing differences for CG are much smaller (16s for cmfrec vs 16.5s for rsparse), while the Cholesky solver is slightly faster in rsparse (29.5s vs 31s - might be because cmfrec replaces some BLAS calls that run slow on amd64 with 'for' loops).

**Pull request merged**
