### PR TITLE
Avoid possible errors with large matrices

### PR DESCRIPTION
**Pull request by david-cortes**
When initializing the factor matrices, if the number of entries is above `INT_MAX`, the number of entries will be treated as a floating point number, which at that range will have a precision of less than integer, and as such might leave some factors as zeros. This PR avoids it by first allocating a matrix with the right dimensions and then filling it element-by-element in C++, which allows iterating with integer types larger than R's.

### CODE REVIEW

**Comment by dselivanov** [comment]
I think it might be simpler to use arma random number generators as it can fill R matrices in place and both float and double). Let me think about this issue and try how it will work.

**Comment by david-cortes** [comment]
I'm not sure that's a good idea. Armadillo AFAIK uses an LCG algorithm for RNG. From some experiments I've done with different software that require randomness, I always get slightly worse results from LCG algorithms than from MT (R uses MT), even if LCG is supposed to have better properties.

**Comment by dselivanov** [comment]
Seems RcppArmadillo allows to use R's RNG within armadillo - https://stackoverflow.com/a/41266817/1069256

**Comment by dselivanov** [comment]
I'm going to merge this. May be will revisit later to make it use arma for double and float.

**Pull request merged**
