### PR TITLE
Faster CSR slicing

### PR DESCRIPTION
**Pull request by david-cortes**
When slicing a CSR matrix, the procedure will always make checks on the columns to include and create-fill-concatenate R lists, which is slow for a very common use case:
```r
X[1:10000, ]
```
or similar.

Currently, running code like that in a large matrix will be many times slower than creating a matrix from scratch. This PR adds faster code paths when slicing or selecting rows with all columns included.

### CODE REVIEW

**Comment by david-cortes** [comment]
Hmm, seems it somehow broke the column matching loop when passing unordered entries, even though it didn't change anything inside the loop (e.g. `m_csr[, c(5,4,2,3,7)]` will fail due to the output having unsorted column indices), will check why that happens.

**Comment by david-cortes** [comment]
Redid the column reindexing loop in C++ in order to avoid potential problems. It uses `unordered_map` so it's probably not the best way of doing it, but it works correctly and should be faster now. Also added more tests for edge cases.

**Comment by david-cortes** [comment]
Apologies for the large amount of commits. I'm now reasonably sure that it will work correctly under all circumstances while still being faster than before. I've also added more special cases to the tests to be sure.

**Comment by dselivanov** [comment]
Thanks for your contribution. It will take couple of days to review.

**Comment by david-cortes** [comment]
Come to think about more potential special cases, I just realized that with the code currently in master, slicing with an empty vector (e.g. integer(0)) will produce incorrect dimension names. I've also fixed that now and added tests.

**Comment by david-cortes** [comment]
Come to think about it, an even simpler way of doing this is by letting `Matrix` do all the heavy lifting:
```r
subset_csr = function(x, i, j, drop = TRUE) {

  if(missing(i) && missing(j)) return(x)

  csc = new("dgCMatrix")
  csc@p = x@p
  csc@i = x@j
  csc@x = x@x
  csc@Dim = rev(dim(x))
  csc@Dimnames = list(x@Dimnames[[2L]], x@Dimnames[[1L]])

  if (!missing(i) && !missing(j)) {
    csc = csc[j, i, drop=drop]
  } else if (!missing(i)) {
    csc = csc[, i, drop=drop]
  } else {
    csc = csc[j, , drop=drop]
  }

  if (!("dgCMatrix" %in% class(csc)))
    return(csc)

  res = new("dgRMatrix")
  res@p = csc@p
  res@j = csc@i
  res@x = csc@x
  res@Dim = rev(dim(csc))
  res@Dimnames = list(csc@Dimnames[[2L]], csc@Dimnames[[1L]])
  return(res)
}
```

Although it ends up being an order of magnitude slower for selecting a few rows.

**Comment by dselivanov** [comment]
This is more or less how it is done in Matrix pkg.  Overall selecting rows
from CSC matrix is slow and selecting columns from CSR is slow.

Main idea was to avoid costly conversions csr-csc when selecting rows from
CSR matrix (which is common because we mainly use CSR format here).

**Comment by david-cortes** [comment]
Here's a benchmark I did:
```r
library("rsparse")
nr = 1e6
nc = 1e4
set.seed(123)
m = Matrix::rsparsematrix(nrow = nr, ncol = nc, density = 0.01)
m = as(m, "RsparseMatrix")

microbenchmark::microbenchmark(m[1:100000,], times=10L)
microbenchmark::microbenchmark(m[, 1:5000], times=10L)
microbenchmark::microbenchmark(m[1:100000, 1:5000], times=10L)
microbenchmark::microbenchmark(m[rev(1:100000), rev(1:5000)], times=10L)

set.seed(123)
rnd_rows = sample(nr, 1e3)
rnd_cols = sample(nc, 1e3)
microbenchmark::microbenchmark(m[rnd_rows, rnd_cols], times=10L)

microbenchmark::microbenchmark(m[1, ,drop=FALSE], times=100L)
microbenchmark::microbenchmark(m[, 1,drop=FALSE], times=10L)
```

Times when letting `Matrix` do the heavy lifting:
```
Unit: milliseconds
         expr     min      lq     mean   median       uq      max neval
 m[1:1e+05, ] 161.983 165.546 169.8215 168.6199 174.9898 180.8518    10
Unit: milliseconds
        expr      min       lq     mean   median       uq      max neval
 m[, 1:5000] 547.8655 555.0041 574.1004 560.5978 567.7516 697.7062    10
Unit: milliseconds
               expr      min       lq     mean  median       uq      max neval
 m[1:1e+05, 1:5000] 153.9114 155.2935 156.2229 155.745 157.8266 158.2122    10
Unit: milliseconds
                         expr      min       lq     mean   median       uq      max neval
 m[rev(1:1e+05), rev(1:5000)] 325.0255 328.9749 337.9809 332.6801 339.5985 378.5209    10
----------
Unit: milliseconds
                  expr      min      lq     mean   median       uq      max neval
 m[rnd_rows, rnd_cols] 111.5895 112.695 113.0358 112.9264 113.6979 114.4002    10
----------
Unit: milliseconds
                 expr      min       lq     mean   median       uq      max neval
 m[1, , drop = FALSE] 106.3051 108.8743 111.7308 111.3634 113.5287 129.7651   100
Unit: milliseconds
                 expr      min       lq     mean   median       uq      max neval
 m[, 1, drop = FALSE] 306.1975 307.9531 331.7948 334.6119 347.6339 373.8139    10
```

Times with this PR:
```
Unit: milliseconds
         expr      min       lq     mean   median     uq      max neval
 m[1:1e+05, ] 77.33024 79.53785 88.68761 81.88077 85.823 143.3555    10
Unit: milliseconds
        expr      min       lq     mean   median       uq      max neval
 m[, 1:5000] 360.8222 363.7683 382.5475 368.2354 376.6981 505.4463    10
Unit: milliseconds
               expr      min       lq     mean  median       uq      max neval
 m[1:1e+05, 1:5000] 38.23431 38.81596 43.71872 39.5785 42.91085 76.06585    10
Unit: milliseconds
                         expr      min       lq     mean   median       uq      max neval
 m[rev(1:1e+05), rev(1:5000)] 157.6356 159.5456 165.4118 166.9193 170.4248 172.8375    10
----------
Unit: milliseconds
                  expr      min       lq     mean  median       uq      max neval
 m[rnd_rows, rnd_cols] 2.419718 2.425529 2.515256 2.46315 2.520247 2.892004    10
----------
Unit: microseconds
                 expr     min     lq     mean median       uq      max neval
 m[1, , drop = FALSE] 242.134 247.97 280.1983 250.46 254.1715 2966.243   100
Unit: milliseconds
                 expr      min       lq    mean  median       uq      max neval
 m[, 1, drop = FALSE] 209.2076 211.1041 212.345 212.275 213.9685 215.6825    10
```

**Comment by dselivanov** [comment]
Indeed approach when Matrix does all the heavy lifting looks interesting. Main concern is in making CSC duplcate of the CSR matrix. If CSR matrix is huge then it will increase memory pressure significantly.

**Comment by dselivanov** [comment]
> Main concern is in making CSC duplcate of the CSR matrix. If CSR matrix is huge then it will increase memory pressure significantly.
Actually I was wrong, following code doesn't make duplicate:
```r
csc = new("dgCMatrix")
csc@p = x@p
csc@i = x@j
csc@x = x@x
csc@Dim = rev(dim(x))
csc@Dimnames = list(x@Dimnames[[2L]], x@Dimnames[[1L]])
```

**Comment by dselivanov** [comment]
@david-cortes thanks a lot for the PR, that was a lot of work. 
I completely agree with you that using Matrix pkg for heavy lifting is quite cool. And it is very competitive except one case(IMO very important) when selecting few rows.

**Pull request merged**
